#!/bin/sh
printf "Pre-Push Hook: "

# Analyze the project
# change to use `fvm flutter analyze` when using FVM
flutter analyze

if [ $? -ne 0 ]; then
		printf "Issues with Flutter Analyze found, aborting push"
    exit 1
fi